### ISSUE TITLE
[Bug] Name of this song

### ISSUE THREAD

**Issue by TiagoDanin** [cstyan/spotifySkin#1]
Is not displaying the name of the song
![image](https://cloud.githubusercontent.com/assets/5731176/8438791/7466e9e2-1f3e-11e5-805c-80f5a1977725.png)

**Comment by cstyan** [comment]
Recent changes to the Spotify client and the library in Rainmeter mean I'm going to have to update the portion of my plugin that gets the song name, but I haven't been able to get to it yet.  However, the play/pause/etc. buttons should still work

**Comment by TiagoDanin** [comment]
The buttons are normal

**Comment by cstyan** [comment]
@TiagoDanin fixed
